name: Fibbot
description: My workflow in Rust
inputs:
  args:
    description: Arguments passed to `fibbot`
    required: true
    default: ''
outputs:
  results:
    description: The results from calling `fibbot`
runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.args }}
