name: Fibbot
description: A GitHub Action written in Rust
branding:
  icon: align-left
  color: blue

inputs:
  enable_fib:
    description: 'Enable Fibonacci sequence generation'
    required: true
    default: 'true'
  max_threshold:
    description: 'Maximum threshold for Fibonacci sequence'
    required: true
    default: '100'
  args:
    description: Arguments passed to `Fibbot`
    required: false  

outputs:
  results:
    description: The results from calling `Fibbot`

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.args }}




