name: Fibbot
description: A GitHub Action written in Rust to calculate Fibonacci numbers from a Pull Request contents

inputs:
  enable_fib:
    description: 'Enable Fibonacci sequence generation'
    required: true
    default: 'true'
  max_threshold:
    description: 'Maximum number for fibonacci calcuation'
    required: true
    default: '100'
runs:
  using: "composite"
  #image: "Dockerfile"
  steps: 
    - name: Build Fibbot
      run: cargo build --release
      shell: bash

    - name: Run Fibbot 
      run: |
        export PR_NUMBER="${{ inputs.pr_number }}"
        export GITHUB_TOKEN="${{ inputs.github_token }}"
        ./target/binary "${{ inputs.enable_fib }}" "${{ inputs.max_threshold }}"
      shell: bash 




