name: Fibbot
description: 'A GitHub Action to calculate Fibonacci numbers from PR content.'
inputs:
  enable_fib:
    description: 'Enable Fibonacci calculation'
    required: true
    default: 'true'
  max_threshold:
    description: 'Maximum number for Fibonacci calculation'
    required: true
<<<<<<< HEAD
    default: "100"
  github_token: 
    description: "getting github"
    required: true
  pr_number: 
    description: "getting github"
    required: true

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

      run: cargo build --release

    - name: Run
      run: ./target/release/fibbot
    
=======
    default: '100'
>>>>>>> refs/remotes/origin/master
runs:
  using: "composite"
  # image: 'Dockerfile'
  steps:
    - name: Build FibBot
      run: cargo build --release
      shell: bash

    - name: Run Fibbot
      run: |
        export PR_NUMBER="${{ inputs.pr_number }}"
        export GITHUB_TOKEN="${{ inputs.github_token }}"
        ./target/release/fibbot "${{ inputs.enable_fib }}" "${{ inputs.max_threshold }}"
      shell: bash
