name: Fibbot
description: 'A GitHub Action to calculate Fibonacci numbers from the contents of a PR.'
inputs:
  enable_fib:
    description: 'Enable Fibonacci calculation'
    required: true
    default: 'true'
  max_threshold:
    description: 'Maximum number for Fibonacci calculation'
    required: true
    default: '100'
  github_token:
    description: 'GitHub token for authentication'
    required: true
  pr_number:
    description: 'Pull Request number'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build FibBot
      run: cargo build --release
      shell: bash

    - name: Run FibBot
      run: |
        export PR_NUMBER="${{ inputs.pr_number }}"
        export GITHUB_TOKEN="${{ inputs.github_token }}"
        ./target/release/fibbot "${{ inputs.enable_fib }}" "${{ inputs.max_threshold }}"
      shell: bash