name: fibbot
description: an action to confirm hello world and the fibonacci numbers of the number extracted from the pull request printed on logs

inputs:
  enable_fib:
    description: "Enables the fibonacci calculation"
    required: false
    default: "true"
  max_threshold:
    description: "Provides the maximum value for which the fibonacci function should take "
    required: true
    default: "100"
  github_token: 
    description: "getting github"
    required: true
  pr_number: 
    description: "getting github"
    required: true

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

      run: cargo build --release

    - name: Run
      run: ./target/release/fibbot
    
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.enable_fib }}
    - ${{ inputs.max_threshold }}

   

