name: MyApp
author: Jérome Eertmans
description: A GitHub Action written in Rust
branding:  # You can change this
  icon: align-left
  color: blue
inputs:
  enable_fib:
    description: 'Enable Fibonacci sequence generation'
    required: true
    default: 'false'
  max_threshold:
    description: 'Maximum threshold for Fibonacci sequence'
    required: true
    default: '100'
  args:
    description: Arguments passed to `myapp`
    required: true
    default: ''
outputs:
  results:
    description: The results from calling `myapp`
runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.args }}
