name: Rust Action

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
permissions:
  pull-requests: write
  contents: read

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: cargo build

      - name: Run my Rust action
        uses: ./
        env:
          ENABLE_FIB: "true"
          MAX_THRESHOLD: "100"
