on:
  push:
    branches:
      - master
  pull_request:
   types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set PR_NUMBER
        run: |
          if [ -z "${{ github.event.pull_request.number }}" ]; then
            echo "PR_NUMBER=0" >> $GITHUB_ENV
          else
            echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          fi

      - name: Build and run fibbot
        run: |
          cargo build --release
          ./target/release/fibbot "true" "100"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
